name: Call Collection Run
on:
  schedule:
    - cron: 0 14 * * *
  workflow_dispatch: null
jobs:
  call-workflow:
    uses: digital-land/collection-template/.github/workflows/callable_run.yml@dev
    secrets: inherit

